
# Name of the project
name: 'haunted_houses'
version: '1.0.0'

# Which "profile" dbt uses for this project.
profile: 'my-snowflake-db'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"


models:
  haunted_houses:

    staging:
      +materialized: view
      +schema: STAGING

    marts:
      +materialized: view
      +schema: MART

seeds:
  haunted_houses:
    +schema: RAW
    +quote_columns: false
