my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: uuaznry-pyc50972

      # User/password auth
      user: butoj
      password: Ds0g\xDBo[?&7M9y]3lt

      role: ACCOUNTADMIN
      database: PORTFOLIO_DB
      warehouse: COMPUTE_WH
      schema: staging
      threads: 1
      client_session_keep_alive: False
      query_tag: staging

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None